apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    kind: flask
  namespace: devops
spec:
  containers:
  - image: localhost:5000/oussema/webapp:v3
    name: webapp
    volumeMounts:
    - name: firebase-auth
      mountPath: /app/auth
      readOnly: true
  serviceAccountName: webapp  
  imagePullSecrets:
  - name: registrypullsecret
  volumes:
  - name: firebase-auth
    secret:
      secretName: firebase-secret
      
    
