apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: microfocus:cdf:itom-vault
  namespace: devops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: webapp
subjects:
- kind: ServiceAccount
  name: webapp
  namespace: devops
