apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: jenkins
 labels:
  type: jenkins
spec:
 selector:
  matchLabels:
   type: jenkins
 replicas: 1
 template:
  metadata:
   name: jenkins
   labels:
    type: jenkins
  spec:
   containers:
   - image: jenkins/jenkins:lts-jdk11
     name: jenkins-backend
     volumeMounts:
     - name: jenkins-home
       mountPath: /var/jenkins_home
   volumes:
   - name: jenkins-home
     persistentVolumeClaim:
      claimName: jenkins-home
---
apiVersion: v1
kind: Service
metadata:
 name: jenkins
spec:
 type: NodePort
 ports:
 - nodePort: 8080
   port: 8080
   targetPort: 8080
 selector: 
   type: jenkins   
#docker run -p 8080:8080 -p 50000:50000 -v jenkins_home:/var/jenkins_home jenkins/jenkins:lts-jdk11
